/*
Robin Johnson
4/29/24

This script imports dummy data into the customer tables
*/

-- Inserts dummy customers into CustomerInfo table
INSERT INTO CustomerInfo
    (FName,LName,Email)
VALUES
    ('James', 'Butt', 'jbutt@gmail.com'),
    ('Josephine', 'Darakjy', 'josephine_darakjy@darakjy.org'),
    ('Art', 'Venere', 'art@venere.org'),
    ('Lenna', 'Paprocki', 'lpaprocki@hotmail.com'),
    ('Donette', 'Foller', 'donette.foller@cox.net'),
    ('Simona', 'Morasca', 'simona@morasca.com'),
    ('Mitsue', 'Tollner', 'mitsue_tollner@yahoo.com'),
    ('Leota', 'Dilliard', 'leota@hotmail.com'),
    ('Sage', 'Wieser', 'sage_wieser@cox.net'),
    ('Kris', 'Marrier', 'kris@gmail.com'),
    ('Minna', 'Amigon', 'minna_amigon@yahoo.com'),
    ('Abel', 'Maclead', 'amaclead@gmail.com'),
    ('Kiley', 'Caldarera', 'kiley.caldarera@aol.com'),
    ('Graciela', 'Ruta', 'gruta@cox.net'),
    ('Cammy', 'Albares', 'calbares@gmail.com'),
    ('Mattie', 'Poquette', 'mattie@aol.com'),
    ('Meaghan', 'Garufi', 'meaghan@hotmail.com'),
    ('Gladys', 'Rim', 'gladys.rim@rim.org'),
    ('Yuki', 'Whobrey', 'yuki_whobrey@aol.com'),
    ('Fletcher', 'Flosi', 'fletcher.flosi@yahoo.com'),
    ('Bette', 'Nicka', 'bette_nicka@cox.net'),
    ('Veronika', 'Inouye', 'vinouye@aol.com'),
    ('Willard', 'Kolmetz', 'willard@hotmail.com'),
    ('Maryann', 'Royster', 'mroyster@royster.com'),
    ('Alisha', 'Slusarski', 'alisha@slusarski.com'),
    ('Allene', 'Iturbide', 'allene_iturbide@cox.net'),
    ('Chanel', 'Caudy', 'chanel.caudy@caudy.org'),
    ('Ezekiel', 'Chui', 'ezekiel@chui.com'),
    ('Willow', 'Kusko', 'wkusko@yahoo.com'),
    ('Bernardo', 'Figeroa', 'bfigeroa@aol.com'),
    ('Ammie', 'Corrio', 'ammie@corrio.com'),
    ('Francine', 'Vocelka', 'francine_vocelka@vocelka.com'),
    ('Ernie', 'Stenseth', 'ernie_stenseth@aol.com'),
    ('Albina', 'Glick', 'albina@glick.com'),
    ('Alishia', 'Sergi', 'asergi@gmail.com'),
    ('Solange', 'Shinko', 'solange@shinko.com'),
    ('Jose', 'Stockham', 'jose@yahoo.com'),
    ('Rozella', 'Ostrosky', 'rozella.ostrosky@ostrosky.com'),
    ('Valentine', 'Gillian', 'valentine_gillian@gmail.com'),
    ('Kati', 'Rulapaugh', 'kati.rulapaugh@hotmail.com'),
    ('Youlanda', 'Schemmer', 'youlanda@aol.com'),
    ('Dyan', 'Oldroyd', 'doldroyd@aol.com'),
    ('Roxane', 'Campain', 'roxane@hotmail.com'),
    ('Lavera', 'Perin', 'lperin@perin.org'),
    ('Erick', 'Ferencz', 'erick.ferencz@aol.com'),
    ('Fatima', 'Saylors', 'fsaylors@saylors.org'),
    ('Jina', 'Briddick', 'jina_briddick@briddick.com'),
    ('Kanisha', 'Waycott', 'kanisha_waycott@yahoo.com'),
    ('Emerson', 'Bowley', 'emerson.bowley@bowley.org'),
    ('Blair', 'Malet', 'bmalet@yahoo.com'),
    ('Brock', 'Bolognia', 'bbolognia@yahoo.com'),
    ('Lorrie', 'Nestle', 'lnestle@hotmail.com'),
    ('Sabra', 'Uyetake', 'sabra@uyetake.org'),
    ('Marjory', 'Mastella', 'mmastella@mastella.com'),
    ('Karl', 'Klonowski', 'karl_klonowski@yahoo.com'),
    ('Tonette', 'Wenner', 'twenner@aol.com'),
    ('Amber', 'Monarrez', 'amber_monarrez@monarrez.org'),
    ('Shenika', 'Seewald', 'shenika@gmail.com'),
    ('Delmy', 'Ahle', 'delmy.ahle@hotmail.com');
GO

-- Inserts dummy addresses into CustomerAddresses table
INSERT INTO CustomerAddresses
    (StreetAddress, City, State, ZipCode)
VALUES
    ('6649 N Blue Gum St', 'New Orleans', 'LA', 70116),
    ('4 B Blue Ridge Blvd', 'Brighton', 'MI', 48116),
    ('8 W Cerritos Ave #54', 'Bridgeport', 'NJ', 8014),
    ('639 Main St', 'Anchorage', 'AK', 99501),
    ('34 Center St', 'Hamilton', 'OH', 45011),
    ('3 Mcauley Dr', 'Ashland', 'OH', 44805),
    ('7 Eads St', 'Chicago', 'IL', 60632),
    ('7 W Jackson Blvd', 'San Jose', 'CA', 95111),
    ('5 Boston Ave #88', 'Sioux Falls', 'SD', 57105),
    ('228 Runamuck Pl #2808', 'Baltimore', 'MD', 21224),
    ('2371 Jerrold Ave', 'Kulpsville', 'PA', 19443),
    ('37275 St Rt 17m M', 'Middle Island', 'NY', 11953),
    ('25 E 75th St #69', 'Los Angeles', 'CA', 90034),
    ('98 Connecticut Ave Nw', 'Chagrin Falls', 'OH', 44023),
    ('56 E Morehead St', 'Laredo', 'TX', 78045),
    ('73 State Road 434 E', 'Phoenix', 'AZ', 85013),
    ('69734 E Carrillo St', 'Mc Minnville', 'TN', 37110),
    ('322 New Horizon Blvd', 'Milwaukee', 'WI', 53207),
    ('1 State Route 27', 'Taylor', 'MI', 48180),
    ('394 Manchester Blvd', 'Rockford', 'IL', 61109),
    ('6 S 33rd St', 'Aston', 'PA', 19014),
    ('6 Greenleaf Ave', 'San Jose', 'CA', 95111),
    ('618 W Yakima Ave', 'Irving', 'TX', 75062),
    ('74 S Westgate St', 'Albany', 'NY', 12204),
    ('3273 State St', 'Middlesex', 'NJ', 8846),
    ('1 Central Ave', 'Stevens Point', 'WI', 54481),
    ('86 Nw 66th St #8673', 'Shawnee', 'KS', 66218),
    ('2 Cedar Ave #84', 'Easton', 'MD', 21601),
    ('90991 Thorburn Ave', 'New York', 'NY', 10011),
    ('386 9th Ave N', 'Conroe', 'TX', 77301),
    ('74874 Atlantic Ave', 'Columbus', 'OH', 43215),
    ('366 South Dr', 'Las Cruces', 'NM', 88011),
    ('45 E Liberty St', 'Ridgefield Park', 'NJ', 7660),
    ('4 Ralph Ct', 'Dunellen', 'NJ', 8812),
    ('2742 Distribution Way', 'New York', 'NY', 10025),
    ('426 Wolf St', 'Metairie', 'LA', 70002),
    ('128 Bransten Rd', 'New York', 'NY', 10011),
    ('17 Morena Blvd', 'Camarillo', 'CA', 93012),
    ('775 W 17th St', 'San Antonio', 'TX', 78204),
    ('6980 Dorsett Rd', 'Abilene', 'KS', 67410),
    ('2881 Lewis Rd', 'Prineville', 'OR', 97754),
    ('7219 Woodfield Rd', 'Overland Park', 'KS', 66204),
    ('1048 Main St', 'Fairbanks', 'AK', 99708),
    ('678 3rd Ave', 'Miami', 'FL', 33196),
    ('20 S Babcock St', 'Fairbanks', 'AK', 99712),
    ('2 Lighthouse Ave', 'Hopkins', 'MN', 55343),
    ('38938 Park Blvd', 'Boston', 'MA', 2128),
    ('5 Tomahawk Dr', 'Los Angeles', 'CA', 90006),
    ('762 S Main St', 'Madison', 'WI', 53711),
    ('209 Decker Dr', 'Philadelphia', 'PA', 19132),
    ('4486 W O St #1', 'New York', 'NY', 10003),
    ('39 S 7th St', 'Tullahoma', 'TN', 37388),
    ('98839 Hawthorne Blvd #6101', 'Columbia', 'SC', 29201),
    ('71 San Mateo Ave', 'Wayne', 'PA', 19087),
    ('76 Brooks St #9', 'Flemington', 'NJ', 8822),
    ('4545 Courthouse Rd', 'Westbury', 'NY', 11590),
    ('14288 Foster Ave #4121', 'Jenkintown', 'PA', 19046),
    ('4 Otis St', 'Van Nuys', 'CA', 91405),
    ('65895 S 16th St', 'Providence', 'RI', 2909);
GO